# Configurations
markdown: kramdown
markdown_ext:  markdown,mkdown,mkdn,mkd,md
highlighter: pygments

# Needed for backward compatibility
gems: [jekyll-paginate]

# Permalinks
permalink:        /blog/:year/:month/:day/:title

# Setup
title:            'Yoshua Nava'
tagline:          'Aspiring roboticist'
description:      'Personal webpage'
#url:              'http://127.0.0.1:4000'
url:              http://yoshuanava.github.io
repository:		  http://www.github.com/YoshuaNava/yoshuanava.github.io
baseurl:          ''

# Navigation
navigation:
- text: About
  url: /about/
- text: Resume
  url: /resume/
- text: Blog
  url: /blog/
#- text: Tags
#  url: /tags/
- text: Projects
  url : /projects/
- text: Search
  url: /search/


# Author Details
author:          'Yoshua Nava'

#Social Media links (Use complete URL except for email)
email:		  yoshua.nava.chocron@gmail.com
youtube: "http://www.youtube.com/channel/UCbF_buNB5MRenUcW9du5RdA"
github: "http://github.com/YoshuaNava"
linkedin: "http://ve.linkedin.com/in/yoshuanavachocron"
stack-exchange: "http://stackexchange.com/users/5531488/yoshuanava"
disqus_shortname: "YoshuaNava"
gplus: "https://plus.google.com/u/0/109288294525578115012"


# Google Analytics
#gahandler: 'UA-52149651-1'

#if footersvg is 'true' the social media links will be shown top on the copy right in the footer
footersvg: 'true'

# Disqus
disqushandler: 'yoshuanava'

# Blog Configurations
paginate: 10 # Posts per page on the blog index
paginate_path: '/blog/page:num'
destination: ./_site

# Custom vars
version:          0.9x beta 2
