name: Yoshua Nava
url: http://yoshuanava.github.io
description: Informatics engineer - Future robotics researcher

permalink: /:year/:month/:day/:title/
paginate: 10
pygments: true

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
