# Site settings
title: "Freelancer"
email: "yoshua.nava.chocron@gmail.com"
description: "My name is Yoshua Nava. I'm an informatics engineer from Universidad Católica Andrés Bello, Caracas, Venezuela. My main dream is to pursue a career in robotics research. This is my blog and portfolio."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F
  
# Footer settings
footer:
  copyright: Dr. Henry Jekyll
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: "http://twitter.com/popopopote"
  - title: linkedin
    url: "http://ve.linkedin.com/in/yoshuanavachocron"
  - title: stackexchange
    url: "http://stackexchange.com/users/5531488/yoshuanava"
  - title: youtube
    url: "http://www.youtube.com/channel/UCbF_buNB5MRenUcW9du5RdA"
  - title: github
    url: "http://github.com/yoshuanava"

# Postal address (add as many lines as necessary)
address:
  - line: Caracas
  - line: Venezuela
  
# Credits content
credits: 'Freelance is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty
